GENDER_CHOICES = (
    ('female', 'Female'),
    ('male', 'Male'),
    ('non_binary', 'Non-Binary'),
    ('trans_female', 'Transgender Female'),
    ('trans_male', 'Transgender Male'),
    ('prefer_not_to_say', 'Prefer not to say'),
    ('other', 'Other'),
)

ETHNICITY_CHOICES = (
    ('hispanic_latino', 'Hispanic or Latino'),
    ('white', 'White'),
    ('black_african_american', 'African American'),
    ('asian', 'Asian'),
    ('american_indian_alaska_native', 'American Indian or Alaska Native'),
    ('native_hawaiian_pacific_islander', 'Native Hawaiian or Other Pacific Islander'),
    ('middle_eastern', 'Middle Eastern'),
    ('mixed_race', 'Mixed Race'),
    ('other', 'Other'),
    ('prefer_not_to_say', 'Prefer not to say'),
)

INCOME_RANGES = [
    ('0-25', 'Less than £25,000'),
    ('25-50', '£25,000 - £49,999'),
    ('50-75', '£50,000 - £74,999'),
    ('75-100', '£75,000 - £99,999'),
    ('100+', '£100,000 or more'),
    ('prefer_not_to_say', 'Prefer not to say'),
]

MARITAL_STATUS_CHOICES = (
    ('single', 'Single'),
    ('married', 'Married'),
    ('divorced', 'Divorced'),
    ('widowed', 'Widowed'),
    ('separated', 'Separated'),
    ('in_civil_union', 'In a Civil Union'),
    ('in_domestic_partnership', 'In a Domestic Partnership'),
    ('prefer_not_to_say', 'Prefer not to say'),
    ('other', 'Other'),
)

CURRENT_EDUCATION_LEVEL_CHOICES = (
    ('', 'none'),
    ('no_formal_education', 'No Formal Education'),
    ('some_primary', 'Some Primary Education'),
    ('completed_primary', 'Completed Primary Education'),
    ('some_secondary', 'Some Secondary Education'),
    ('completed_secondary', 'Completed Secondary Education'),
    ('some_college', 'Some College'),
    ('associate_degree', 'Associate Degree'),
    ('bachelor_degree', 'Bachelor’s Degree'),
    ('master_degree', 'Master’s Degree'),
    ('professional_degree', 'Professional Degree (e.g., MD, JD)'),
    ('doctorate', 'Doctorate (PhD, EdD)'),
    ('other', 'Other'),
    ('prefer_not_to_say', 'Prefer not to say'),
)

STUDY_LEVEL_CHOICES = [
    ('', 'none'),
    ('associate_degree', "Undergraduate (Associate's)"),
    ('bachelor_degree', "Undergraduate (Bachelor's)"),
    ('postgraduate', 'Postgraduate'),
    ('doctorate', "Doctorate"),
    ('not_sure', 'Not sure'),
    ('prefer_not_to_say', 'Prefer not to say'),
]

STUDY_TIME_CHOICES = [
    ('part_time', 'Part Time'),
    ('full_time', 'Full Time'),
    ('not_sure', 'Not sure'),
    ('prefer_not_to_say', 'Prefer not to say'),
]

APPRENTICE_LEVEL_CHOICES = [
    ('', 'none'),
    ('intermediate', 'Intermediate'),
    ('advanced', 'Advanced'),
    ('higher', 'Higher'),
    ('degree', 'Degree')
]

OVERSEAS_STATUS = [
    ('home','Home'),
    ('overseas','Overseas'),
    ('dont_know/prefer_not_to_say', "Don't know/Prefer not to say")
]

RELIGION_CHOICES = [
    ('no_religion', 'No religion'),
    ('atheism', 'Atheism'),
    ('christianity', 'Christianity'),
    ('islam', 'Islam'),
    ('hinduism', 'Hinduism'),
    ('buddhism', 'Buddhism'),
    ('sikhism', 'Sikhism'),
    ('judaism', 'Judaism'),
    ('bahai', 'Bahá’í Faith'),
    ('jainism', 'Jainism'),
    ('shinto', 'Shinto'),
    ('taoism', 'Taoism'),
    ('confucianism', 'Confucianism'),
    ('zoroastrianism', 'Zoroastrianism'),
    ('paganism', 'Paganism'),
    ('agnosticism', 'Agnosticism'),
    ('interfaith', 'Interfaith'),
    ('other', 'Other'),
    ('prefer_not_to_say', 'Prefer not to say')
]

DISABILITY_CHOICES = [
    ("yes", "Yes"),
    ("no", "No"),
    ("prefer_not_to_say", "Prefer not to say"),
]

COUNTRIES = [
    ("Afghanistan","Afghanistan"),
    ("Albania","Albania"),
    ("Algeria","Algeria"),
    ("American Samoa","American Samoa"),
    ("Andorra","Andorra"),
    ("Angola","Angola"),
    ("Anguilla","Anguilla"),
    ("Antarctica","Antarctica"),
    ("Antigua and Barbuda","Antigua and Barbuda"),
    ("Argentina","Argentina"),
    ("Armenia","Armenia"),
    ("Aruba","Aruba"),
    ("Australia","Australia"),
    ("Austria","Austria"),
    ("Azerbaijan","Azerbaijan"),
    ("Bahamas","Bahamas"),
    ("Bahrain","Bahrain"),
    ("Bangladesh","Bangladesh"),
    ("Barbados","Barbados"),
    ("Belarus","Belarus"),
    ("Belgium","Belgium"),
    ("Belize","Belize"),
    ("Benin","Benin"),
    ("Bermuda","Bermuda"),
    ("Bhutan","Bhutan"),
    ("Bolivia","Bolivia"),
    ("Bosnia and Herzegovina","Bosnia and Herzegovina"),
    ("Botswana","Botswana"),
    ("Brazil","Brazil"),
    ("Brunei Darussalam","Brunei Darussalam"),
    ("Bulgaria","Bulgaria"),
    ("Burkina Faso","Burkina Faso"),
    ("Burundi","Burundi"),
    ("Cambodia","Cambodia"),
    ("Cameroon","Cameroon"),
    ("Canada","Canada"),
    ("Cape Verde","Cape Verde"),
    ("Cayman Islands","Cayman Islands"),
    ("Central African Republic","Central African Republic"),
    ("Chad","Chad"),
    ("Chile","Chile"),
    ("China","China"),
    ("Christmas Island","Christmas Island"),
    ("Cocos Islands","Cocos Islands"),
    ("Colombia","Colombia"),
    ("Comoros","Comoros"),
    ("Republic of Congo","Republic of Congo"),
    ("Cook Islands","Cook Islands"),
    ("Costa Rica","Costa Rica"),
    ("Ivory Coast","Ivory Coast"),
    ("Croatia","Croatia"),
    ("Cuba","Cuba"),
    ("Cyprus","Cyprus"),
    ("Czech Republic","Czech Republic"),
    ("Democratic Republic of the Congo","Democratic Republic of the Congo"),
    ("Denmark","Denmark"),
    ("Djibouti","Djibouti"),
    ("Dominica","Dominica"),
    ("Dominican Republic","Dominican Republic"),
    ("East Timor","East Timor"),
    ("Ecuador","Ecuador"),
    ("Egypt","Egypt"),
    ("El Salvador","El Salvador"),
    ("Equatorial Guinea","Equatorial Guinea"),
    ("Eritrea","Eritrea"),
    ("Estonia","Estonia"),
    ("Ethiopia","Ethiopia"),
    ("Falkland Islands","Falkland Islands"),
    ("Faroe Islands","Faroe Islands"),
    ("Fiji","Fiji"),
    ("Finland","Finland"),
    ("France","France"),
    ("French Guiana","French Guiana"),
    ("French Polynesia","French Polynesia"),
    ("French Southern Territories","French Southern Territories"),
    ("Gabon","Gabon"),
    ("Georgia","Georgia"),
    ("Germany","Germany"),
    ("Ghana","Ghana"),
    ("Gibraltar","Gibraltar"),
    ("Greece","Greece"),
    ("Greenland","Greenland"),
    ("Grenada","Grenada"),
    ("Guadeloupe","Guadeloupe"),
    ("Guam","Guam"),
    ("Guatemala","Guatemala"),
    ("Guinea","Guinea"),
    ("Guinea-Bissau","Guinea-Bissau"),
    ("Guyana","Guyana"),
    ("Haiti","Haiti"),
    ("Holy See","Holy See"),
    ("Honduras","Honduras"),
    ("Hong Kong","Hong Kong"),
    ("Hungary","Hungary"),
    ("Iceland","Iceland"),
    ("India","India"),
    ("Indonesia","Indonesia"),
    ("Iran","Iran"),
    ("Iraq","Iraq"),
    ("Ireland","Ireland"),
    ("Israel","Israel"),
    ("Italy","Italy"),
    ("Ivory Coast","Ivory Coast"),
    ("Jamaica","Jamaica"),
    ("Japan","Japan"),
    ("Jordan","Jordan"),
    ("Kazakhstan","Kazakhstan"),
    ("Kenya","Kenya"),
    ("Kiribati","Kiribati"),
    ("North Korea","North Korea"),
    ("South Korea","South Korea"),
    ("Kuwait","Kuwait"),
    ("Kyrgyzstan","Kyrgyzstan"),
    ("Lao","Lao"),
    ("Latvia","Latvia"),
    ("Lebanon","Lebanon"),
    ("Lesotho","Lesotho"),
    ("Liberia","Liberia"),
    ("Libya","Libya"),
    ("Liechtenstein","Liechtenstein"),
    ("Lithuania","Lithuania"),
    ("Luxembourg","Luxembourg"),
    ("Macau","Macau"),
    ("Madagascar","Madagascar"),
    ("Malawi","Malawi"),
    ("Malaysia","Malaysia"),
    ("Maldives","Maldives"),
    ("Mali","Mali"),
    ("Malta","Malta"),
    ("Marshall Islands","Marshall Islands"),
    ("Martinique","Martinique"),
    ("Mauritania","Mauritania"),
    ("Mauritius","Mauritius"),
    ("Mayotte","Mayotte"),
    ("Mexico","Mexico"),
    ("Micronesia","Micronesia"),
    ("Moldova","Moldova"),
    ("Monaco","Monaco"),
    ("Mongolia","Mongolia"),
    ("Montenegro","Montenegro"),
    ("Montserrat","Montserrat"),
    ("Morocco","Morocco"),
    ("Mozambique","Mozambique"),
    ("Myanmar","Myanmar"),
    ("Namibia","Namibia"),
    ("Nauru","Nauru"),
    ("Nepal","Nepal"),
    ("Netherlands","Netherlands"),
    ("Netherlands Antilles","Netherlands Antilles"),
    ("New Caledonia","New Caledonia"),
    ("New Zealand","New Zealand"),
    ("Nicaragua","Nicaragua"),
    ("Niger","Niger"),
    ("Nigeria","Nigeria"),
    ("Niue","Niue"),
    ("North Macedonia","North Macedonia"),
    ("Northern Mariana Islands","Northern Mariana Islands"),
    ("Norway","Norway"),
    ("Oman","Oman"),
    ("Pakistan","Pakistan"),
    ("Palau","Palau"),
    ("Palestinian territories","Palestinian territories"),
    ("Panama","Panama"),
    ("Papua New Guinea","Papua New Guinea"),
    ("Paraguay","Paraguay"),
    ("Peru","Peru"),
    ("Philippines","Philippines"),
    ("Pitcairn Island","Pitcairn Island"),
    ("Poland","Poland"),
    ("Portugal","Portugal"),
    ("Puerto Rico","Puerto Rico"),
    ("Qatar","Qatar"),
    ("Reunion Island","Reunion Island"),
    ("Romania","Romania"),
    ("Russia","Russia"),
    ("Rwanda","Rwanda"),
    ("Saint Kitts and Nevis","Saint Kitts and Nevis"),
    ("Saint Lucia","Saint Lucia"),
    ("Saint Vincent and the Grenadines","Saint Vincent and the Grenadines"),
    ("Samoa","Samoa"),
    ("San Marino","San Marino"),
    ("Sao Tome and Principe","Sao Tome and Principe"),
    ("Saudi Arabia","Saudi Arabia"),
    ("Senegal","Senegal"),
    ("Serbia","Serbia"),
    ("Seychelles","Seychelles"),
    ("Sierra Leone","Sierra Leone"),
    ("Singapore","Singapore"),
    ("Slovakia","Slovakia"),
    ("Slovenia","Slovenia"),
    ("Solomon Islands","Solomon Islands"),
    ("Somalia","Somalia"),
    ("South Africa","South Africa"),
    ("South Sudan","South Sudan"),
    ("Spain","Spain"),
    ("Sri Lanka","Sri Lanka"),
    ("Sudan","Sudan"),
    ("Suriname","Suriname"),
    ("Swaziland","Swaziland"),
    ("Sweden","Sweden"),
    ("Switzerland","Switzerland"),
    ("Syria","Syria"),
    ("Taiwan","Taiwan"),
    ("Tajikistan","Tajikistan"),
    ("Tanzania","Tanzania"),
    ("Thailand","Thailand"),
    ("The Gambia","The Gambia"),
    ("Tibet","Tibet"),
    ("Timor-Leste","Timor-Leste"),
    ("Togo","Togo"),
    ("Tokelau","Tokelau"),
    ("Tonga","Tonga"),
    ("Trinidad and Tobago","Trinidad and Tobago"),
    ("Tunisia","Tunisia"),
    ("Turkey","Turkey"),
    ("Turkmenistan","Turkmenistan"),
    ("Turks and Caicos","Turks and Caicos"),
    ("Tuvalu","Tuvalu"),
    ("Uganda","Uganda"),
    ("Ukraine","Ukraine"),
    ("United Arab Emirates","United Arab Emirates"),
    ("United Kingdom","United Kingdom"),
    ("United States","United States"),
    ("Uruguay","Uruguay"),
    ("Uzbekistan","Uzbekistan"),
    ("Vanuatu","Vanuatu"),
    ("Vatican City State","Vatican City State"),
    ("Venezuela","Venezuela"),
    ("Vietnam","Vietnam"),
    ("British Virgin Islands","British Virgin Islands"),
    ("United States Virgin Islands","United States Virgin Islands"),
    ("Wallis and Futuna Islands","Wallis and Futuna Islands"),
    ("Western Sahara","Western Sahara"),
    ("Yemen","Yemen"),
    ("Zambia","Zambia"),
    ("Zimbabwe","Zimbabwe")
]